FROM simpledms-base

WORKDIR /app

# Copy frontend code
COPY frontend/ .

# Set Python path
ENV PYTHONPATH=/app

# Expose the Streamlit port
EXPOSE 8501

# Start the Streamlit app
CMD ["streamlit", "run", "main.py", "--server.address", "0.0.0.0"] 